# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobtask', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_def',
            name='filepath',
        ),
        migrations.AddField(
            model_name='task_def',
            name='file',
            field=models.FileField(null=True, upload_to='upload/%Y/%m/%d', verbose_name='\u6587\u4ef6\u8def\u5f84'),
        ),
    ]
