# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='website',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
