# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20170807_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='book.Author', verbose_name='\u4f5c\u8005'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u51fa\u7248\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Publisher', verbose_name='\u51fa\u7248\u793e'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=64, verbose_name='\u4e66\u540d'),
        ),
    ]
