# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comm_Job_Def',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func', models.TextField(verbose_name='\u529f\u80fd\u8bf4\u660e')),
                ('job_status', models.SmallIntegerField(verbose_name='\u4efb\u52a1\u72b6\u6001')),
                ('job_type', models.SmallIntegerField(verbose_name='\u4efb\u52a1\u7c7b\u578b')),
                ('job_perm_status', models.SmallIntegerField(verbose_name='\u4efb\u52a1\u6743\u9650\u72b6\u6001')),
                ('create_user', models.CharField(max_length=64, verbose_name='\u521b\u5efa\u7528\u6237')),
                ('create_dt', models.DateTimeField(verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_dt', models.DateTimeField(blank=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('note', models.TextField(verbose_name='\u5907\u6ce8')),
            ],
        ),
        migrations.CreateModel(
            name='Comm_Task_Def',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func', models.TextField(verbose_name='\u529f\u80fd\u8bf4\u660e')),
                ('exe_user', models.CharField(max_length=64, verbose_name='\u6267\u884c\u7528\u6237')),
                ('params', models.TextField(verbose_name='\u53c2\u6570')),
                ('create_user', models.CharField(max_length=64, verbose_name='\u521b\u5efa\u7528\u6237')),
                ('create_dt', models.DateTimeField(verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_dt', models.DateTimeField(blank=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('iphosts', models.TextField(verbose_name='IP\u6216\u4e3b\u673a\u540d')),
                ('timeout', models.IntegerField(verbose_name='\u8d85\u65f6\u65f6\u95f4')),
                ('note', models.TextField(verbose_name='\u5907\u6ce8')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobid', models.CharField(max_length=64, verbose_name='\u4f5c\u4e1aID')),
                ('create_dt', models.DateTimeField(verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_dt', models.DateTimeField(blank=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('job_status', models.SmallIntegerField(verbose_name='\u4f5c\u4e1a\u72b6\u6001')),
            ],
        ),
        migrations.CreateModel(
            name='Job_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exe_user', models.CharField(max_length=64, verbose_name='\u6267\u884c\u7528\u6237')),
                ('params', models.TextField(verbose_name='\u53c2\u6570')),
                ('iphosts', models.TextField(verbose_name='IP\u6216\u4e3b\u673a\u540d')),
                ('timeout', models.IntegerField(verbose_name='\u8d85\u65f6\u65f6\u95f4')),
                ('fromip', models.CharField(max_length=16, verbose_name='\u4efb\u52a1\u72b6\u6001')),
                ('create_user', models.CharField(max_length=64, verbose_name='\u521b\u5efa\u7528\u6237')),
                ('create_dt', models.DateTimeField(verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_dt', models.DateTimeField(blank=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('note', models.TextField(verbose_name='\u5907\u6ce8')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobtask.Job', verbose_name='\u4efb\u52a1\u5b9a\u4e49')),
            ],
        ),
        migrations.CreateModel(
            name='Res_Control_Conf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem', models.IntegerField(verbose_name='\u5185\u5b58\u8981\u6c42(M)')),
                ('mem_percent', models.IntegerField(verbose_name='\u5185\u5b58\u8981\u6c42(%)')),
                ('sys_load_1', models.FloatField(verbose_name='\u7cfb\u7edf\u8d1f\u8f7d\u8981\u6c42(1m)')),
                ('sys_load_5', models.FloatField(verbose_name='\u7cfb\u7edf\u8d1f\u8f7d\u8981\u6c42(5m)')),
                ('sys_load_15', models.FloatField(verbose_name='\u7cfb\u7edf\u8d1f\u8f7d\u8981\u6c42(15m)')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', models.TextField(verbose_name='\u53c2\u6570')),
                ('executor', models.CharField(max_length=16, verbose_name='\u89e3\u6790\u5668')),
                ('exe_user', models.CharField(max_length=16, verbose_name='\u6267\u884c\u7528\u6237')),
                ('iphost', models.TextField(verbose_name='IP\u6216\u4e3b\u673a\u540d')),
                ('create_dt', models.DateTimeField(verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_dt', models.DateTimeField(blank=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('task_status', models.SmallIntegerField(verbose_name='\u4efb\u52a1\u72b6\u6001')),
                ('note', models.TextField(verbose_name='\u5907\u6ce8')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobtask.Job_task', verbose_name='\u4f5c\u4e1a\u4efb\u52a1')),
            ],
        ),
        migrations.CreateModel(
            name='Task_Def',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_loc', models.SmallIntegerField(blank=True, verbose_name='\u6587\u4ef6\u4f4d\u7f6e')),
                ('file', models.FileField(null=True, upload_to='upload/%Y/%m/%d', verbose_name='\u672c\u5730\u6587\u4ef6')),
                ('remote_file', models.CharField(max_length=255, null=True, verbose_name='\u670d\u52a1\u5668\u7aef\u6587\u4ef6')),
                ('file_type', models.SmallIntegerField(verbose_name='\u6587\u4ef6\u7c7b\u578b')),
                ('main_script_name', models.CharField(max_length=64, verbose_name='\u4e3b\u811a\u672c\u540d')),
                ('params', models.TextField(verbose_name='\u53c2\u6570')),
                ('executor', models.CharField(max_length=16, verbose_name='\u89e3\u6790\u5668')),
                ('func', models.TextField(verbose_name='\u529f\u80fd\u8bf4\u660e')),
                ('task_status', models.SmallIntegerField(verbose_name='\u4efb\u52a1\u72b6\u6001')),
                ('task_type', models.SmallIntegerField(verbose_name='\u4efb\u52a1\u7c7b\u578b')),
                ('task_perm_status', models.SmallIntegerField(verbose_name='\u4efb\u52a1\u6743\u9650\u72b6\u6001')),
                ('create_user', models.CharField(max_length=64, verbose_name='\u521b\u5efa\u7528\u6237')),
                ('create_dt', models.DateTimeField(blank=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_dt', models.DateTimeField(blank=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('note', models.TextField(verbose_name='\u5907\u6ce8')),
                ('res_ctl_conf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobtask.Res_Control_Conf', verbose_name='\u4e3b\u673a\u8d44\u6e90\u63a7\u5236')),
            ],
        ),
        migrations.AddField(
            model_name='job_task',
            name='task_def_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobtask.Task_Def', verbose_name='\u4efb\u52a1\u5b9a\u4e49'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['jobid'], name='jobid_idx'),
        ),
        migrations.AddField(
            model_name='comm_task_def',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobtask.Task_Def', verbose_name='\u4efb\u52a1\u5b9a\u4e49'),
        ),
        migrations.AddField(
            model_name='comm_job_def',
            name='comm_tasks',
            field=models.ManyToManyField(to='jobtask.Comm_Task_Def', verbose_name='\u4efb\u52a1\u5217\u8868'),
        ),
    ]
