# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobtask', '0002_auto_20170920_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobclass', models.CharField(max_length=32, verbose_name='\u4f5c\u4e1a\u5206\u7c7b')),
                ('jobtype_cn', models.CharField(max_length=32, verbose_name='\u4f5c\u4e1a\u5206\u7c7b(CN)')),
                ('create_user', models.CharField(max_length=64, verbose_name='\u521b\u5efa\u7528\u6237')),
                ('create_dt', models.DateTimeField(blank=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_dt', models.DateTimeField(blank=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('note', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
            ],
        ),
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobstatus', models.CharField(max_length=32, verbose_name='\u4f5c\u4e1a\u72b6\u6001')),
                ('jobstatus_cn', models.CharField(max_length=32, verbose_name='\u4f5c\u4e1a\u72b6\u6001(CN)')),
                ('create_user', models.CharField(max_length=64, verbose_name='\u521b\u5efa\u7528\u6237')),
                ('create_dt', models.DateTimeField(blank=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_dt', models.DateTimeField(blank=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('note', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtype', models.CharField(max_length=32, verbose_name='\u4f5c\u4e1a\u7c7b\u578b')),
                ('jobtype_cn', models.CharField(max_length=32, verbose_name='\u4f5c\u4e1a\u7c7b\u578b(CN)')),
                ('create_user', models.CharField(max_length=64, verbose_name='\u521b\u5efa\u7528\u6237')),
                ('create_dt', models.DateTimeField(blank=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_dt', models.DateTimeField(blank=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('note', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
            ],
        ),
        migrations.RemoveField(
            model_name='comm_job_def',
            name='job_perm_status',
        ),
        migrations.AlterField(
            model_name='comm_job_def',
            name='job_status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobtask.JobStatus', verbose_name='\u4f5c\u4e1a\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='comm_job_def',
            name='job_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobtask.JobType', verbose_name='\u4f5c\u4e1a\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='comm_task_def',
            name='params',
            field=models.TextField(blank=True, null=True, verbose_name='\u53c2\u6570'),
        ),
        migrations.AlterField(
            model_name='task_def',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='upload/%Y/%m/%d', verbose_name='\u672c\u5730\u6587\u4ef6'),
        ),
        migrations.AddField(
            model_name='comm_job_def',
            name='job_class',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobtask.JobClass', verbose_name='\u4f5c\u4e1a\u5206\u7c7b'),
        ),
    ]
