# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 03:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobtask', '0003_auto_20170924_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comm_job_def',
            name='job_type',
        ),
    ]
