# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 03:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobtask', '0004_remove_comm_job_def_job_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobclass',
            old_name='jobtype_cn',
            new_name='jobclass_cn',
        ),
    ]
