# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobtask', '0005_auto_20170924_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='comm_job_def',
            name='jobtype',
            field=models.IntegerField(default=2, verbose_name='\u4efb\u52a1\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='comm_task_def',
            name='tasktype',
            field=models.IntegerField(default=2, verbose_name='\u4efb\u52a1\u7c7b\u578b'),
        ),
    ]
