# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobtask', '0006_auto_20170924_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_task',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='job_task',
            name='task_def_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='job',
        ),
        migrations.AddField(
            model_name='job',
            name='jobdef',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobtask.Comm_Job_Def', verbose_name='\u4f5c\u4e1a'),
        ),
        migrations.AddField(
            model_name='job_task',
            name='comm_task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobtask.Comm_Task_Def', verbose_name='\u4efb\u52a1\u5b9a\u4e49'),
        ),
        migrations.AddField(
            model_name='job_task',
            name='job',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobtask.Job', verbose_name='\u4f5c\u4e1a'),
        ),
        migrations.AddField(
            model_name='task',
            name='jobtask',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobtask.Job_task', verbose_name='\u4f5c\u4e1a\u4efb\u52a1'),
        ),
        migrations.AddField(
            model_name='task',
            name='retcode',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='\u6267\u884c\u8fd4\u56de\u7801'),
        ),
        migrations.AddField(
            model_name='task',
            name='stderr',
            field=models.TextField(blank=True, null=True, verbose_name='\u6807\u51c6\u9519\u8bef\u8f93\u51fa'),
        ),
        migrations.AddField(
            model_name='task',
            name='stdout',
            field=models.TextField(blank=True, null=True, verbose_name='\u6807\u51c6\u8f93\u51fa'),
        ),
        migrations.AddField(
            model_name='task',
            name='taskdef',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobtask.Task_Def', verbose_name='\u4efb\u52a1\u5b9a\u4e49'),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobid',
            field=models.CharField(max_length=64, verbose_name='\u4f5c\u4e1a\u5355\u53f7'),
        ),
    ]
