# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobtask', '0007_auto_20170924_0553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_SubTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', models.TextField(verbose_name='\u53c2\u6570')),
                ('executor', models.CharField(max_length=16, verbose_name='\u89e3\u6790\u5668')),
                ('exe_user', models.CharField(max_length=16, verbose_name='\u6267\u884c\u7528\u6237')),
                ('iphost', models.TextField(verbose_name='IP\u6216\u4e3b\u673a\u540d')),
                ('create_dt', models.DateTimeField(verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_dt', models.DateTimeField(blank=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('task_status', models.SmallIntegerField(blank=True, null=True, verbose_name='\u4efb\u52a1\u72b6\u6001')),
                ('retcode', models.SmallIntegerField(blank=True, null=True, verbose_name='\u6267\u884c\u8fd4\u56de\u7801')),
                ('stdout', models.TextField(blank=True, null=True, verbose_name='\u6807\u51c6\u8f93\u51fa')),
                ('stderr', models.TextField(blank=True, null=True, verbose_name='\u6807\u51c6\u9519\u8bef\u8f93\u51fa')),
                ('note', models.TextField(verbose_name='\u5907\u6ce8')),
            ],
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', models.TextField(verbose_name='\u53c2\u6570')),
                ('executor', models.CharField(max_length=16, verbose_name='\u89e3\u6790\u5668')),
                ('exe_user', models.CharField(max_length=16, verbose_name='\u6267\u884c\u7528\u6237')),
                ('iphost', models.TextField(verbose_name='IP\u6216\u4e3b\u673a\u540d')),
                ('create_dt', models.DateTimeField(verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_dt', models.DateTimeField(blank=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('task_status', models.SmallIntegerField(blank=True, null=True, verbose_name='\u4efb\u52a1\u72b6\u6001')),
                ('retcode', models.SmallIntegerField(blank=True, null=True, verbose_name='\u6267\u884c\u8fd4\u56de\u7801')),
                ('stdout', models.TextField(blank=True, null=True, verbose_name='\u6807\u51c6\u8f93\u51fa')),
                ('stderr', models.TextField(blank=True, null=True, verbose_name='\u6807\u51c6\u9519\u8bef\u8f93\u51fa')),
                ('note', models.TextField(verbose_name='\u5907\u6ce8')),
            ],
        ),
        migrations.RenameField(
            model_name='task',
            old_name='iphost',
            new_name='iphosts',
        ),
        migrations.RemoveField(
            model_name='task',
            name='executor',
        ),
        migrations.RemoveField(
            model_name='task',
            name='jobtask',
        ),
        migrations.RemoveField(
            model_name='task',
            name='retcode',
        ),
        migrations.RemoveField(
            model_name='task',
            name='stderr',
        ),
        migrations.RemoveField(
            model_name='task',
            name='stdout',
        ),
        migrations.RemoveField(
            model_name='task',
            name='taskdef',
        ),
        migrations.AddField(
            model_name='job_task',
            name='job_task_status',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='\u4efb\u52a1\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='task',
            name='create_user',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u521b\u5efa\u7528\u6237'),
        ),
        migrations.AddField(
            model_name='task',
            name='fromip',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='\u4efb\u52a1\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='task',
            name='taskid',
            field=models.CharField(max_length=64, null=True, verbose_name='\u4efb\u52a1\u53f7'),
        ),
        migrations.AddField(
            model_name='task',
            name='timeout',
            field=models.IntegerField(default=0, verbose_name='\u8d85\u65f6\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='task',
            name='exe_user',
            field=models.CharField(max_length=64, verbose_name='\u6267\u884c\u7528\u6237'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='\u4efb\u52a1\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='jobtask',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobtask.Job_task', verbose_name='\u4f5c\u4e1a\u4efb\u52a1'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='taskdef',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobtask.Task_Def', verbose_name='\u4efb\u52a1\u5b9a\u4e49'),
        ),
        migrations.AddField(
            model_name='job_subtask',
            name='jobtask',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobtask.Job_task', verbose_name='\u4f5c\u4e1a\u4efb\u52a1'),
        ),
        migrations.AddField(
            model_name='job_subtask',
            name='taskdef',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobtask.Task_Def', verbose_name='\u4efb\u52a1\u5b9a\u4e49'),
        ),
    ]
