# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobtask', '0008_auto_20170926_1203'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comm_job_def',
            table='comm_job_def',
        ),
        migrations.AlterModelTable(
            name='comm_task_def',
            table='comm_task_def',
        ),
        migrations.AlterModelTable(
            name='job',
            table='job',
        ),
        migrations.AlterModelTable(
            name='job_subtask',
            table='job_subtask',
        ),
        migrations.AlterModelTable(
            name='job_task',
            table='job_task',
        ),
        migrations.AlterModelTable(
            name='jobclass',
            table='job_class',
        ),
        migrations.AlterModelTable(
            name='jobstatus',
            table='job_status',
        ),
        migrations.AlterModelTable(
            name='jobtype',
            table='job_type',
        ),
        migrations.AlterModelTable(
            name='res_control_conf',
            table='res_control_conf',
        ),
        migrations.AlterModelTable(
            name='saltminion',
            table='saltminion',
        ),
        migrations.AlterModelTable(
            name='subtask',
            table='subtask',
        ),
        migrations.AlterModelTable(
            name='task',
            table='task',
        ),
        migrations.AlterModelTable(
            name='task_def',
            table='task_def',
        ),
    ]
