# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobtask', '0009_auto_20170926_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_subtask',
            name='taskdef',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='taskdef',
        ),
        migrations.AddField(
            model_name='job_subtask',
            name='file',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u670d\u52a1\u5668\u7aef\u6587\u4ef6'),
        ),
        migrations.AddField(
            model_name='job_subtask',
            name='file_loc',
            field=models.SmallIntegerField(blank=True, default=1, verbose_name='\u6587\u4ef6\u4f4d\u7f6e'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='file',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u670d\u52a1\u5668\u7aef\u6587\u4ef6'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='file_loc',
            field=models.SmallIntegerField(blank=True, default=1, verbose_name='\u6587\u4ef6\u4f4d\u7f6e'),
        ),
    ]
