# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobtask', '0010_auto_20170926_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='create_user',
            field=models.CharField(max_length=64, null=True, verbose_name='\u521b\u5efa\u7528\u6237'),
        ),
    ]
