# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobtask', '0013_auto_20170926_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_class',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobtask.JobClass', verbose_name='\u4f5c\u4e1a\u5206\u7c7b'),
        ),
        migrations.AlterField(
            model_name='job_subtask',
            name='jobtask',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='job_sub_task', to='jobtask.Job_task', verbose_name='\u4f5c\u4e1a\u4efb\u52a1'),
        ),
        migrations.AlterField(
            model_name='job_task',
            name='job',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='job_tasks', to='jobtask.Job', verbose_name='\u4f5c\u4e1a'),
        ),
    ]
