# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobtask', '0014_auto_20170927_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_subtask',
            name='jobtask',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='job_sub_tasks', to='jobtask.Job_task', verbose_name='\u4f5c\u4e1a\u4efb\u52a1'),
        ),
        migrations.AlterField(
            model_name='job_task',
            name='comm_task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comm_tasks', to='jobtask.Comm_Task_Def', verbose_name='\u4efb\u52a1\u5b9a\u4e49'),
        ),
    ]
