# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobtask', '0015_auto_20170927_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_subtask',
            name='main_script_name',
            field=models.CharField(default='', max_length=64, verbose_name='\u4e3b\u6267\u884c\u7a0b\u5e8f'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='main_script_name',
            field=models.CharField(default='', max_length=64, verbose_name='\u4e3b\u6267\u884c\u7a0b\u5e8f'),
        ),
        migrations.AlterField(
            model_name='job_subtask',
            name='file',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u6587\u4ef6\u8def\u5f84'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='file',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u6587\u4ef6\u8def\u5f84'),
        ),
        migrations.AlterField(
            model_name='task_def',
            name='main_script_name',
            field=models.CharField(max_length=64, verbose_name='\u4e3b\u6267\u884c\u7a0b\u5e8f'),
        ),
    ]
