# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobtask', '0016_auto_20170927_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_subtask',
            name='jobtask',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='job_sub_tasks', to='jobtask.Job_Task', verbose_name='\u4f5c\u4e1a\u4efb\u52a1'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='jobtask',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobtask.Job_Task', verbose_name='\u4f5c\u4e1a\u4efb\u52a1'),
        ),
    ]
