# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobtask', '0017_auto_20171005_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_task',
            name='file',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u6587\u4ef6\u8def\u5f84'),
        ),
        migrations.AddField(
            model_name='job_task',
            name='file_loc',
            field=models.SmallIntegerField(default=1, verbose_name='\u6587\u4ef6\u4f4d\u7f6e'),
        ),
        migrations.AddField(
            model_name='job_task',
            name='main_script_name',
            field=models.CharField(default='', max_length=64, verbose_name='\u4e3b\u6267\u884c\u7a0b\u5e8f'),
        ),
        migrations.AlterField(
            model_name='job_subtask',
            name='jobtask',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='job_sub_tasks', to='jobtask.Job_Task', verbose_name='\u4f5c\u4e1a\u4efb\u52a1'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='jobtask',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobtask.Job_Task', verbose_name='\u4f5c\u4e1a\u4efb\u52a1'),
        ),
    ]
